let readline = require('readline-sync')

let nome = readline.question("Digite seu nome: ")
let idade = readline.question("Digite sua idade: ")
let diaNasc = readline.question("Digite o dia que vc nasceu: ")
let mesNasc = readline.question("Digite o mês que vc nasceu: ")
let anoNasc = readline.question("Digite o ano em que vc nasceu: ")
let cpf = readline.question("Digite seu cpf: ")
let email = readline.question("Digite seu email: ")
let telefone = readline.question("Digite seu telefone: ")
let cidade = readline.question("Digite sua cidade: ")
let estado = readline.question("Digite seu estado: ")
let profissao = readline.question("Digite sua profissão: ")

console.log("\n-------------FORMULÁRIO----------------")
console.log(`Nome: ${nome}`)
console.log("Data de Nascimento: " + diaNasc + "/" + mesNasc + "/" + anoNasc)
console.log(`Idade: ${idade}`)
console.log(`CPF: ${cpf}`)
console.log(`Email: ${email}`)
console.log(`Telefone: ${telefone}`)
console.log(`Cidade: ${cidade}`)
console.log(`Estado: ${estado}`)
console.log(`Profissão: ${profissao}`)